# Generated by Django 3.1.7 on 2021-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
