# Generated by Django 3.1.7 on 2021-04-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
