# Generated by Django 3.1.7 on 2021-04-13 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_relation_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
