# Generated by Django 3.1.7 on 2021-04-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_relation_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, max_length=12, null=True),
        ),
    ]
